# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - deploy

medias.cc-front:
  stage: deploy
  image: ubuntu
  tags: [docker]
  before_script:
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - echo $ID_ED25519 > ~/.ssh/id_ed25519.pub
    - apt-get update -y
    - apt-get install -y sshpass
  script:
    - echo $CI_COMMIT_BRANCH
    - if [ "$CI_COMMIT_BRANCH" == "main" ]; then AZ_DOMAIN="$AZ_DOMAIN_MAIN"; else AZ_DOMAIN="$AZ_DOMAIN_DEV"; fi
    - echo ${AZ_DOMAIN}
    - echo ${AZ_ENV}
    - sshpass -p $AZ_SSH_PASSWORD ssh $AZ_USERNAME@${AZ_DOMAIN} "ls -la"
    - sshpass -p $AZ_SSH_PASSWORD ssh $AZ_USERNAME@${AZ_DOMAIN} "source enable_pub_key.sh && cd medias.cc-frontend && git pull origin $CI_COMMIT_BRANCH"
    - sshpass -p $AZ_SSH_PASSWORD ssh $AZ_USERNAME@${AZ_DOMAIN} "sudo service nginx restart all"
  only:
    refs:
      - main
      - dev
